# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
default: &default
  adapter: postgresql 
  pool: 5
  timeout: 5000
  host: localhost
  port: 5432

development:
  <<: *default
  database: wolox_training_development
  username: wolox2
  password: wolox2

test:
  <<: *default
  encoding: unicode
  database: wolox_training_test
  username: wolox2
  password: wolox2