# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c93b75b9d3f58670609b6907409d78b3516b30cc4786242bad83dab370a90928dac58edb8aa296fbd2f506037db98b3c48f9ae7942f86a143fe0687621a95276
  mandrill_key: <%= ENV["MANDRILL_KEY"] %>
  mandrill_username: <%= ENV["MANDRILL_USER"] %>
  mandrill_domain: <%= ENV["MANDRIL_DOMAIN"] %>

test:
  secret_key_base: d13314ba2d48bbdb0e8fb343e39fbc29300b178da876075fe27b50cd61b8fe3991d78a8cb0f172b6481b89b89f8205a9c85906c13fc85a65f9dac240a727490e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  mandrill_key: <%= ENV["MANDRILL_KEY"] %>
  mandrill_username: <%= ENV["MANDRILL_USER"] %>
  mandrill_domain: <%= ENV["MANDRIL_DOMAIN"] %>
